---
name: "Git tag for release-please drafts"
description: "Create git tag for release-please drafts and immutable releases"
inputs:
  tag-prefix:
    description: 'Prefix for the tag (e.g., "v" for "v0.1.0", or empty for "0.1.0")'
    required: false
    default: "v"
  manifest-filename:
    description: "Release-please manifest file name"
    required: false
    default: "./configs/release-please-manifest.json"
  manifest-package:
    description: 'Release-please manifest package (e.g., "packages/backend" for monorepo packages)'
    required: false
    default: "."

outputs:
  package:
    description: "The package name from manifest"
    value: ${{ steps.create-tag.outputs.package }}
  prefix:
    description: "The tag prefix used"
    value: ${{ steps.create-tag.outputs.prefix }}
  manifest_version:
    description: "The raw version from manifest"
    value: ${{ steps.create-tag.outputs.manifest_version }}
  tag_version:
    description: "The final tag version created"
    value: ${{ steps.create-tag.outputs.tag_version }}

runs:
  using: "composite"
  steps:
    - name: Create tag via GitHub script/API
      id: create-tag
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  # v8.0.0
      env:
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        INPUT_MANIFEST_FILENAME: ${{ inputs.manifest-filename }}
        INPUT_MANIFEST_PACKAGE: ${{ inputs.manifest-package }}
      with:
        script: |
          const fs = require('fs');

          const tagPrefix = process.env.INPUT_TAG_PREFIX;
          const manifestFilename = process.env.INPUT_MANIFEST_FILENAME;
          const manifestPackage = process.env.INPUT_MANIFEST_PACKAGE;

          const fileContent = fs.readFileSync(manifestFilename, 'utf8');
          const manifestData = JSON.parse(fileContent);
          const rawVersion = manifestData[manifestPackage];
          const tagVersion = `${tagPrefix}${rawVersion}`;

          core.info(`Package: ${manifestPackage}`);
          core.info(`Prefix: ${tagPrefix}`);
          core.info(`Manifest version: ${rawVersion}`);
          core.info(`Tag version: ${tagVersion}`);

          core.setOutput('package', manifestPackage);
          core.setOutput('prefix', tagPrefix);
          core.setOutput('manifest_version', rawVersion);
          core.setOutput('tag_version', tagVersion);

          try {
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${tagVersion}`,
            });
            core.info(`Tag ${tagVersion} already exists`);
            return;
          } catch (error) {
            if (error.status !== 404) {
              core.setFailed(`Tag get operation failed: HTTP ${error.status}`);
            }
          }

          try {
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagVersion}`,
              sha: context.sha,
            });
          } catch (error) {
            core.setFailed(`Tag creation failed: HTTP ${error.status}`);
          }

          core.notice(`Successfully created tag: ${tagVersion}`);
