---
name: Go Deploy

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      # go-version:
      #   description: "Go version to use"
      #   required: false
      #   default: "stable"
      #   type: string
      go-version-file:
        description: "Go version file to use"
        required: false
        default: "go.mod"
        type: string
      goreleaser-version:
        description: "Goreleaser version"
        required: false
        default: "latest"
        type: string
      goreleaser-args:
        description: "Goreleaser args"
        required: false
        default: "release --clean --config configs/goreleaser.yaml"
        type: string

jobs:
  goreleaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v.6.4.0
        with:
          go-version-file: ${{ inputs.go-version-file }}
      - name: Build and release with goreleaser
        id: releaser
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89  # v7.2.2
        with:
          distribution: goreleaser
          version: ${{ inputs.goreleaser-version }}
          args: ${{ inputs.goreleaser-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **goreleaser** | ${{ steps.releaser.outcome }} |" >> $GITHUB_STEP_SUMMARY
